name: Message Echo 1

on: 
  workflow_dispatch:
    inputs:
      message:
        description: "Message to echo"
        required: true
        # No default

permissions: {}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        env:
          MESSAGE: ${{ inputs.message }}
        run: echo "$MESSAGE"
